# Configurație Dependabot pentru actualizări automate de dependențe
version: 2
updates:
  # Dependențe npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Bucharest"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "Europe/Bucharest"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(actions)"
    labels:
      - "dependencies"
